export const DEMO_SAMPLES = [
  {
    id: 'demo-1',
    label: 'Hindi — High Risk',
    labelHi: 'हिंदी — खतरनाक',
    language: 'Hindi',
    langFlag: '🇮🇳',
    text: 'नमस्ते, मैं SBI बैंक से बोल रहा हूं। आपका खाता 24 घंटे में बंद हो जाएगा। अभी अपना OTP और ATM PIN हमें बताएं।',
    mockResult: {
      riskLevel: 'HIGH_RISK',
      confidenceScore: 96,
      detectedLanguage: 'Hindi',
      threatScores: {
        otpCredentialTheft: 98,
        urgentPaymentDemand: 85,
        authorityImpersonation: 92,
        fearUrgencyTactics: 89,
        personalInfoHarvesting: 76,
      },
      highlightedPhrases: [
        { phrase: 'OTP और ATM PIN', reason: 'OTP/PIN कभी शेयर नहीं करते', severity: 'high' },
        { phrase: 'SBI बैंक से बोल रहा हूं', reason: 'बैंक इस तरह कॉल नहीं करता', severity: 'high' },
        { phrase: '24 घंटे में बंद हो जाएगा', reason: 'डर दिखाकर जल्दी करवाना', severity: 'medium' },
      ],
      explanation: [
        'यह एक फ़ोन बैंकिंग धोखा है',
        'असली SBI कभी OTP नहीं मांगता',
        'तुरंत फ़ोन काटें और 1930 पर कॉल करें',
      ],
      similarPatterns: [
        { name: 'Vishing Scam', description: 'Voice phishing impersonating bank officials' },
        { name: 'OTP Fraud', description: 'Stealing OTP to drain bank accounts' },
      ],
    },
  },
  {
    id: 'demo-2',
    label: 'Marathi — Suspicious',
    labelHi: 'मराठी — संशयास्पद',
    language: 'Marathi',
    langFlag: '🇮🇳',
    text: 'तुमच्या KYC अपडेट न केल्यामुळे तुमचे खाते तात्पुरते बंद केले जाईल. कृपया या लिंकवर क्लिक करा.',
    mockResult: {
      riskLevel: 'SUSPICIOUS',
      confidenceScore: 72,
      detectedLanguage: 'Marathi',
      threatScores: {
        otpCredentialTheft: 30,
        urgentPaymentDemand: 45,
        authorityImpersonation: 65,
        fearUrgencyTactics: 78,
        personalInfoHarvesting: 70,
      },
      highlightedPhrases: [
        { phrase: 'KYC अपडेट', reason: 'KYC अपडेट हे फसवणुकीचे सामान्य कारण', severity: 'medium' },
        { phrase: 'लिंकवर क्लिक करा', reason: 'अज्ञात लिंकवर क्लिक करू नका', severity: 'high' },
        { phrase: 'खाते तात्पुरते बंद', reason: 'भीती निर्माण करणे', severity: 'medium' },
      ],
      explanation: [
        'हा एक संभाव्य KYC फसवणूक संदेश आहे',
        'बँक SMS मधून KYC लिंक पाठवत नाही',
        'बँकेच्या अधिकृत वेबसाइटवर जा',
      ],
      similarPatterns: [
        { name: 'KYC Scam', description: 'Fake KYC update requests to harvest personal data' },
      ],
    },
  },
  {
    id: 'demo-3',
    label: 'Tamil — High Risk',
    labelHi: 'தமிழ் — ஆபத்தானது',
    language: 'Tamil',
    langFlag: '🇮🇳',
    text: 'உங்கள் வங்கி கணக்கு உடனடியாக மூடப்படும். இப்போதே OTP அனுப்புங்கள். இது RBI அறிவிப்பு.',
    mockResult: {
      riskLevel: 'HIGH_RISK',
      confidenceScore: 91,
      detectedLanguage: 'Tamil',
      threatScores: {
        otpCredentialTheft: 95,
        urgentPaymentDemand: 60,
        authorityImpersonation: 88,
        fearUrgencyTactics: 85,
        personalInfoHarvesting: 70,
      },
      highlightedPhrases: [
        { phrase: 'OTP அனுப்புங்கள்', reason: 'OTP ஒருபோதும் பகிர வேண்டாம்', severity: 'high' },
        { phrase: 'RBI அறிவிப்பு', reason: 'RBI நேரடியாக தொடர்பு கொள்ளாது', severity: 'high' },
        { phrase: 'உடனடியாக மூடப்படும்', reason: 'அவசர உணர்வை ஏற்படுத்துவது', severity: 'medium' },
      ],
      explanation: [
        'இது ஒரு வங்கி மோசடி செய்தி',
        'RBI एकபோதும் OTP கேட்காது',
        'உடனடியாக 1930 அழைக்கவும்',
      ],
      similarPatterns: [
        { name: 'RBI Impersonation', description: 'Scammers pretending to be RBI officials' },
        { name: 'Account Freeze Scam', description: 'Threatening account closure to extract OTP' },
      ],
    },
  },
  {
    id: 'demo-4',
    label: 'Hinglish — Suspicious',
    labelHi: 'Hinglish — संदिग्ध',
    language: 'Mixed',
    langFlag: '🇮🇳',
    text: 'Aapka account 2 ghante mein band ho jayega. KYC complete karne ke liye abhi call karein.',
    mockResult: {
      riskLevel: 'SUSPICIOUS',
      confidenceScore: 68,
      detectedLanguage: 'Mixed',
      threatScores: {
        otpCredentialTheft: 25,
        urgentPaymentDemand: 40,
        authorityImpersonation: 50,
        fearUrgencyTactics: 75,
        personalInfoHarvesting: 55,
      },
      highlightedPhrases: [
        { phrase: 'account 2 ghante mein band', reason: 'Creating urgency through fear', severity: 'medium' },
        { phrase: 'KYC complete karne ke liye', reason: 'Common pretext for phishing', severity: 'medium' },
        { phrase: 'abhi call karein', reason: 'Pressuring immediate action', severity: 'low' },
      ],
      explanation: [
        'This message uses urgency tactics common in phishing',
        'Banks don\'t send KYC reminders via informal SMS',
        'Do not call unknown numbers from SMS',
      ],
      similarPatterns: [
        { name: 'KYC Urgency Scam', description: 'Creating fake deadlines for KYC completion' },
      ],
    },
  },
];

export const MOCK_LIVE_CHUNKS = [
  {
    chunkNumber: 1,
    transcript: 'नमस्ते जी, मैं HDFC बैंक से बात कर रहा हूं। आपका अकाउंट में कुछ प्रॉब्लम है।',
    riskLevel: 'LOW',
    confidenceScore: 15,
    threatScores: {
      otpCredentialTheft: 5,
      urgentPaymentDemand: 10,
      authorityImpersonation: 20,
      fearUrgencyTactics: 15,
      personalInfoHarvesting: 10,
    },
    highlightedPhrases: [],
    alertMessage: null,
  },
  {
    chunkNumber: 2,
    transcript: 'आपके खाते में कुछ संदिग्ध गतिविधि हुई है। आपको अभी verify करना होगा नहीं तो account freeze हो जाएगा।',
    riskLevel: 'MEDIUM',
    confidenceScore: 64,
    threatScores: {
      otpCredentialTheft: 30,
      urgentPaymentDemand: 50,
      authorityImpersonation: 60,
      fearUrgencyTactics: 75,
      personalInfoHarvesting: 45,
    },
    highlightedPhrases: [
      { phrase: 'संदिग्ध गतिविधि', reason: 'डर दिखाना', severity: 'medium' },
      { phrase: 'account freeze', reason: 'धमकी देना', severity: 'medium' },
    ],
    alertMessage: null,
  },
  {
    chunkNumber: 3,
    transcript: 'आपको अभी अपना OTP और पासवर्ड बताना होगा। मैं अधिकारी हूं, 10 मिनट में सब ठीक हो जाएगा।',
    riskLevel: 'CRITICAL',
    confidenceScore: 97,
    threatScores: {
      otpCredentialTheft: 99,
      urgentPaymentDemand: 70,
      authorityImpersonation: 90,
      fearUrgencyTactics: 85,
      personalInfoHarvesting: 88,
    },
    highlightedPhrases: [
      { phrase: 'OTP और पासवर्ड बताना होगा', reason: 'OTP कभी शेयर न करें', severity: 'high' },
      { phrase: 'मैं अधिकारी हूं', reason: 'अधिकारी होने का नाटक', severity: 'high' },
    ],
    alertMessage: '🚨 यह धोखा है! अभी फ़ोन काटें!',
  },
];
