export const UI_STRINGS = {
  hi: {
    appName: 'Raksham',
    tagline: 'आपकी भाषा में संपूर्ण सुरक्षा',
    analyze: 'स्मार्ट चेक',
    analyzing: 'जांच हो रही है...',
    safe: 'सुरक्षित',
    suspicious: 'देखें',
    highRisk: 'असुरक्षित',
    hangUp: 'अभी फ़ोन काटें!',
    shareFamily: 'परिवार को सूचित करें',
    report: '1930 पर सहायता लें',
    checkAnother: 'नई जांच करें',
    liveCall: 'कॉल सुरक्षा सक्रिय करें',
    startRecording: 'सुरक्षा शुरू करें',
    stopRecording: 'रोकें',
    uploadAudio: 'ऑडियो अपलोड करें',
    pasteMessage: 'संदेश यहाँ डालें...',
    neverShareOTP: 'OTP एक निजी चाबी है',
    bankNeverAsks: 'बैंक कभी कॉल पर जानकारी नहीं मांगता',
    history: 'सुरक्षा इतिहास',
    about: 'परिचय',
    textAnalysis: 'संदेश सुरक्षा',
    audioUpload: 'ऑडियो सुरक्षा',
    liveCallTab: 'कॉल सुरक्षा',
    uploading: 'भेजा जा रहा है...',
    transcribing: 'प्रोसेस हो रहा है...',
    resultTitle: 'सुरक्षा रिपोर्ट',
    noScans: 'कोई इतिहास नहीं',
    totalScans: 'कुल सुरक्षा जांच',
    highRiskCaught: 'रोके गए खतरे',
    languages: 'समर्थित भाषाएं',
    dragDrop: 'ऑडियो फाइल यहाँ लाएं या क्लिक करें',
    supported: 'समर्थित: MP3, WAV, M4A, WEBM',
    maxSize: 'अधिकतम 20MB',
    time: 'समय',
    language: 'भाषा',
    type: 'प्रकार',
    risk: 'सुरक्षा स्तर',
    score: 'रेटिंग',
    view: 'देखें',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    callCyberCrime: '1930 डायल करें',
    onlineReport: 'Online रिपोर्ट करें',
    safetyTips: 'सुरक्षा के उपाय',
    safetyTip1: 'निजी जानकारी किसी को न दें',
    safetyTip2: 'अज्ञात लिंक पर क्लिक न करें',
    safetyTip3: 'किसी भी संदेह पर 1930 पर संपर्क करें',
    thisIsScam: 'सावधान: यह एक खतरा हो सकता है!',
    hangUpImmediately: 'तुरंत फ़ोन काट दें',
    continueCall: 'जारी रखें',
    requestingMic: 'सुरक्षा के लिए माइक की आवश्यकता है...',
    chunkAnalyzing: 'जांच जारी है...',
    sessionEnded: 'सुरक्षा सत्र समाप्त',
    peakRisk: 'उच्चतम जोखिम',
    chunksAnalyzed: 'विश्लेषित भाग',
    totalDuration: 'कुल समय',
    howItWorks: 'Raksham कैसे काम करता है',
    step1: 'पायरी 1: जानकारी दें',
    step1Desc: 'कोई भी संदिग्ध संदेश या ऑडियो अपलोड करें',
    step2: 'पायरी 2: स्मार्ट चेक',
    step2Desc: 'हमारा सिस्टम भाषा और इरादे का बारीकी से विश्लेषण करता है',
    step3: 'पायरी 3: सुरक्षा रिपोर्ट',
    step3Desc: 'तुरंत सुरक्षा रेटिंग और सुझाव प्राप्त करें',
    heroTitle: 'अपनी भाषा में संपूर्ण डिजिटल सुरक्षा',
    heroSubtitle: 'Raksham: भारत की अपनी तकनीक, जो आपको और आपके परिवार को डिजिटल खतरों से बचाती है।',
    trySample: 'उदाहरण देखें',
    autoDetect: 'ऑटो-डिटेक्ट',
    aboutTitle: 'Raksham के बारे में',
    aboutDesc: 'भारत का पहला बहुभाषी सुरक्षा कवच',
    problemStatement: 'चुनौती',
    solution: 'हमारा समाधान',
    shareWhatsApp: 'WhatsApp पर साझा करें',
  },
  mr: {
    appName: 'Raksham',
    tagline: 'तुमच्या भाषेत संपूर्ण सुरक्षा',
    analyze: 'स्मार्ट चेक',
    analyzing: 'तपासणी सुरू आहे...',
    safe: 'सुरक्षित',
    suspicious: 'तपासा',
    highRisk: 'धोकादायक',
    hangUp: 'आत्ताच फोन ठेवा!',
    shareFamily: 'कुटुंबाला कळवा',
    report: '1930 वर मदत घ्या',
    checkAnother: 'नवीन तपासणी',
    liveCall: 'कॉल सुरक्षा सुरू करा',
    startRecording: 'सुरक्षा सुरू करा',
    stopRecording: 'थांबवा',
    uploadAudio: 'ऑडिओ अपलोड करा',
    pasteMessage: 'संदेश इथे पेस्ट करा...',
    neverShareOTP: 'OTP ही तुमची खाजगी चावी आहे',
    bankNeverAsks: 'बँक कधीही कॉलवर माहिती मागत नाही',
    history: 'सुरक्षा इतिहास',
    about: 'परिचय',
    textAnalysis: 'संदेश सुरक्षा',
    audioUpload: 'ऑडिओ सुरक्षा',
    liveCallTab: 'कॉल सुरक्षा',
    uploading: 'पाठवले जात आहे...',
    transcribing: 'प्रक्रिया सुरू आहे...',
    resultTitle: 'सुरक्षा अहवाल',
    noScans: 'इतिहास नाही',
    totalScans: 'एकूण सुरक्षा तपासण्या',
    highRiskCaught: 'रोखलेले धोके',
    languages: 'समर्थित भाषा',
    dragDrop: 'ऑडिओ फाइल इथे ड्रॅग करा किंवा क्लिक करा',
    supported: 'समर्थित: MP3, WAV, M4A, WEBM',
    maxSize: 'कमाल 20MB',
    time: 'वेळ',
    language: 'भाषा',
    type: 'प्रकार',
    risk: 'सुरक्षा पातळी',
    score: 'रेटिंग',
    view: 'पहा',
    downloadReport: 'अहवाल डाउनलोड करा',
    callCyberCrime: '1930 वर कॉल करा',
    onlineReport: 'Online तक्रार करा',
    safetyTips: 'सुरक्षेचे उपाय',
    safetyTip1: 'खाजगी माहिती कोणालाही देऊ नका',
    safetyTip2: 'अज्ञात लिंकवर क्लिक करू नका',
    safetyTip3: 'कोणत्याही शंकेसाठी 1930 वर संपर्क साधा',
    thisIsScam: 'सावधान: हा एक धोका असू शकतो!',
    hangUpImmediately: 'त्वरित फोन ठेवा',
    continueCall: 'सुरू ठेवा',
    requestingMic: 'सुरक्षेसाठी माइकची आवश्यकता आहे...',
    chunkAnalyzing: 'तपासणी सुरू आहे...',
    sessionEnded: 'सुरक्षा सत्र संपले',
    peakRisk: 'सर्वोच्च धोका',
    chunksAnalyzed: 'विश्लेषित भाग',
    totalDuration: 'एकूण वेळ',
    howItWorks: 'Raksham कसे कार्य करते',
    step1: 'पायरी 1: माहिती द्या',
    step1Desc: 'कोणताही संशयास्पद संदेश किंवा ऑडिओ अपलोड करा',
    step2: 'पायरी 2: स्मार्ट चेक',
    step2Desc: 'आमची प्रणाली भाषा आणि हेतूचे बारकाईने विश्लेषण करते',
    step3: 'पायरी 3: सुरक्षा अहवाल',
    step3Desc: 'तात्काळ सुरक्षा रेटिंग आणि सूचना मिळवा',
    heroTitle: 'तुमच्या भाषेत संपूर्ण डिजिटल सुरक्षा',
    heroSubtitle: 'Raksham: भारताचे स्वतःचे तंत्रज्ञान, जे तुम्हाला आणि तुमच्या कुटुंबाला डिजिटल धोक्यांपासून वाचवते।',
    trySample: 'उदाहरण पहा',
    autoDetect: 'स्वयं ओळख',
    aboutTitle: 'Raksham बद्दल',
    aboutDesc: 'भारताचे पहिले बहुभाषी सुरक्षा कवच',
    problemStatement: 'आव्हान',
    solution: 'आमचा उपाय',
    shareWhatsApp: 'WhatsApp वर पाठवा',
  },
  ta: {
    appName: 'Raksham',
    tagline: 'உங்கள் மொழியில் முழுமையான பாதுகாப்பு',
    analyze: 'ஸ்மார்ட் செக்',
    analyzing: 'ஆய்வு நடைபெறுகிறது...',
    safe: 'பாதுகாப்பானது',
    suspicious: 'கவனிக்கவும்',
    highRisk: 'ஆபத்தானது',
    hangUp: 'இப்போதே ஃபோனை வை!',
    shareFamily: 'குடும்பத்திற்குத் தெரிவிக்கவும்',
    report: '1930-இல் உதவி பெறவும்',
    checkAnother: 'புதிய ஆய்வு',
    liveCall: 'அழைப்பு பாதுகாப்பை இயக்கவும்',
    startRecording: 'பாதுகாப்பைத் தொடங்கு',
    stopRecording: 'நிறுத்து',
    uploadAudio: 'ஆடியோ பதிவேற்று',
    pasteMessage: 'செய்தியை இங்கே ஒட்டவும்...',
    neverShareOTP: 'OTP உங்களின் தனிப்பட்ட கடவுச்சொல்',
    bankNeverAsks: 'வங்கி ஒருபோதும் போனில் தகவல் கேட்காது',
    history: 'பாதுகாப்பு வரலாறு',
    about: 'பற்றி',
    textAnalysis: 'செய்தி பாதுகாப்பு',
    audioUpload: 'ஆடியோ பாதுகாப்பு',
    liveCallTab: 'அழைப்பு பாதுகாப்பு',
    uploading: 'பதிவேற்றப்படுகிறது...',
    transcribing: 'செயலாக்கம் நடைபெறுகிறது...',
    resultTitle: 'பாதுகாப்பு அறிக்கை',
    noScans: 'வரலாறு இல்லை',
    totalScans: 'மொத்த பாதுகாப்பு ஆய்வுகள்',
    highRiskCaught: 'தடுக்கப்பட்ட ஆபத்துகள்',
    languages: 'மொழிகள்',
    dragDrop: 'ஆடியோ கோப்பை இங்கே பதிவேற்றவும்',
    supported: 'ஆதரிக்கப்படுபவை: MP3, WAV, M4A, WEBM',
    maxSize: 'அதிகபட்சம் 20MB',
    time: 'நேரம்',
    language: 'மொழி',
    type: 'வகை',
    risk: 'பாதுகாப்பு நிலை',
    score: 'மதிப்பீடு',
    view: 'பார்',
    downloadReport: 'அறிக்கை பதிவிறக்கம்',
    callCyberCrime: '1930 அழைக்கவும்',
    onlineReport: 'ஆன்லைன் புகார்',
    safetyTips: 'பாதுகாப்பு குறிப்புகள்',
    safetyTip1: 'தனிப்பட்ட தகவலைப் பகிர வேண்டாம்',
    safetyTip2: 'அறியாத இணைப்புகளைத் திறக்க வேண்டாம்',
    safetyTip3: 'சந்தேகம் இருந்தால் 1930-ஐ அழைக்கவும்',
    thisIsScam: 'எச்சரிக்கை: இது ஒரு மோசடியாக இருக்கலாம்!',
    hangUpImmediately: 'இப்போதே ஃபோனை வைக்கவும்',
    continueCall: 'தொடரவும்',
    requestingMic: 'பாதுகாப்பிற்கு மைக்ரோஃபோன் அனுமதி தேவை...',
    chunkAnalyzing: 'பகுப்பாய்வு நடைபெறுகிறது...',
    sessionEnded: 'பாதுகாப்பு அமர்வு முடிந்தது',
    peakRisk: 'அதிகபட்ச ஆபத்து',
    chunksAnalyzed: 'ஆய்வு செய்யப்பட்ட பகுதிகள்',
    totalDuration: 'மொத்த நேரம்',
    howItWorks: 'Raksham எவ்வாறு செயல்படுகிறது',
    step1: 'படி 1: தகவலை வழங்கவும்',
    step1Desc: 'சந்தேகமான செய்தி அல்லது ஆடியோவைப் பதிவேற்றவும்',
    step2: 'படி 2: ஸ்மார்ட் செக்',
    step2Desc: 'எங்கள் அமைப்பு மொழி மற்றும் நோக்கத்தை ஆய்வு செய்கிறது',
    step3: 'படி 3: பாதுகாப்பு அறிக்கை',
    step3Desc: 'உடனடி பாதுகாப்பு மதிப்பீடு மற்றும் ஆலோசனைகளைப் பெறுங்கள்',
    heroTitle: 'உங்கள் மொழியில் முழுமையான டிஜிட்டல் பாதுகாப்பு',
    heroSubtitle: 'Raksham: இந்தியாவின் சொந்தத் தொழில்நுட்பம், உங்களையும் உங்கள் குடும்பத்தையும் டிஜிட்டல் ஆபத்துகளிலிருந்து பாதுகாக்கிறது।',
    trySample: 'உதாரணத்தைப் பார்க்கவும்',
    autoDetect: 'தானியங்கி கண்டறிதல்',
    aboutTitle: 'Raksham பற்றி',
    aboutDesc: 'இந்தியாவின் முதல் பன்மொழி பாதுகாப்பு கவசம்',
    problemStatement: 'சவால்',
    solution: 'எங்கள் தீர்வு',
    shareWhatsApp: 'WhatsApp இல் பகிரவும்',
  },
  en: {
    appName: 'Raksham',
    tagline: 'Universal Safety in Your Language',
    analyze: 'Smart Check',
    analyzing: 'Checking...',
    safe: 'Safe',
    suspicious: 'Suspicious',
    highRisk: 'Unsafe',
    hangUp: 'Hang Up Now!',
    shareFamily: 'Notify Family',
    report: 'Help via 1930',
    checkAnother: 'Check Another',
    liveCall: 'Secure Live Call',
    startRecording: 'Protect Call',
    stopRecording: 'Stop',
    uploadAudio: 'Upload Audio',
    pasteMessage: 'Paste content here...',
    neverShareOTP: 'OTP is your private key',
    bankNeverAsks: 'Real banks never ask for codes over phone',
    history: 'Safety History',
    about: 'Our Mission',
    textAnalysis: 'Message Safety',
    audioUpload: 'Audio Safety',
    liveCallTab: 'Live Protection',
    uploading: 'Sending...',
    transcribing: 'Processing...',
    resultTitle: 'Safety Report',
    noScans: 'No history yet',
    totalScans: 'Total Safety Audits',
    highRiskCaught: 'Threats Blocked',
    languages: 'Supported Languages',
    dragDrop: 'Drag audio here or click to browse',
    supported: 'Format: MP3, WAV, M4A, WEBM',
    maxSize: 'Max 20MB',
    time: 'Time',
    language: 'Language',
    type: 'Type',
    risk: 'Safety Level',
    score: 'Safety Rating',
    view: 'Review',
    downloadReport: 'Save Report',
    callCyberCrime: 'Dial 1930',
    onlineReport: 'Report Online',
    safetyTips: 'Safety Guidelines',
    safetyTip1: 'Avoid sharing personal codes',
    safetyTip2: 'Be wary of unknown links',
    safetyTip3: 'Trust your gut, or check with Raksham',
    thisIsScam: 'WARNING: Potential Fraud!',
    hangUpImmediately: 'HANG UP IMMEDIATELY',
    continueCall: 'Continue',
    requestingMic: 'Enabling protection microphone...',
    chunkAnalyzing: 'Analyzing...',
    sessionEnded: 'Session Secured',
    peakRisk: 'Peak Threat Level',
    chunksAnalyzed: 'Segments Audited',
    totalDuration: 'Total Time',
    howItWorks: 'How Raksham Protects You',
    step1: 'Step 1: Provide Content',
    step1Desc: 'Upload or paste any suspicious message or call recording',
    step2: 'Step 2: Smart Check',
    step2Desc: 'Our system analyzes intent across multiple languages',
    step3: 'Step 3: Safety Report',
    step3Desc: 'Receive an instant safety rating and guidance',
    heroTitle: 'Universal Security in the Language You Speak',
    heroSubtitle: 'Real-time protection against scams, fraud, and digital threats.',
    trySample: 'View Examples',
    autoDetect: 'Auto-detect',
    aboutTitle: 'About Raksham',
    aboutDesc: 'India\'s first comprehensive multilingual safety shield',
    problemStatement: 'The Challenge',
    solution: 'Our Solution',
    shareWhatsApp: 'Share via WhatsApp',
  },
};

export function getUIStrings(lang) {
  return UI_STRINGS[lang] || UI_STRINGS.en;
}

export function detectUILanguage() {
  if (typeof window === 'undefined') return 'en';
  const stored = localStorage.getItem('phishshield-lang');
  if (stored && UI_STRINGS[stored]) return stored;
  const nav = navigator.language?.toLowerCase() || '';
  if (nav.startsWith('hi')) return 'hi';
  if (nav.startsWith('mr')) return 'mr';
  if (nav.startsWith('ta')) return 'ta';
  return 'en';
}
